### ISSUE TITLE
替换代替词

### ISSUE THREAD

**Issue by hecoococ** [heyManNice/sbEncryptor#1]
我希望把‘傻比’替换成我同学的名字，但是在编辑器中用ctrl+F替换后打开的并没有原版那个界面，功能还是有。怎么做保证这个界面也是一样的呢？我不懂html，但是对这个很感兴趣。

**Comment by heyManNice** [comment]
把这个项目fork或者下载之后，在index.html文件中查找“傻”和“比”关键字替换成你的目标关键字，再找到“傻比”一词替换成你的目标关键词，保存后重新使用浏览器打开index.html即可
